### ISSUE TITLE
Not working with React Native

### ISSUE THREAD

**Issue by kiwicopple** [supabase/gotrue-js#11]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

This library isn't working with React native because it tries to access `localstorage`.

## Details

In ReactNative, there is no `localstorage`, it is instead `AsyncStorage`. We need to rewrite any calls to localstorage to guard against this. It might be better to split out all storage calls to a helper file so that we can extend it in the future.

**Comment by kiwicopple** [comment]
Possible alternative approach by Yuyi: https://github.com/yuya-fujimoto/supabase-js/commit/986d6f09c99df371c01beb50bd84bdb81de6f3f5

**Comment by izqalan** [comment]
I got it to work on react-native app (#14 ) but only `auth.signIn` doesn't seem to work as expected on react-native app. 

after digging through the code it seems like `api.signInWithEmail` `results` retruns `400` `Could not read password grant params: EOF` on React-Native app. It work fine on postman and on example app.

my Implementation. (the same as in `/example/src/app.js`)
![https://i.imgur.com/J0bfbEP.png](https://i.imgur.com/J0bfbEP.png)

**Comment by kiwicopple** [comment]
Hey @izqalan I merged your changes as they are a great start. I'll leave this open until we have a chance to fix the bug on `api.signInWithEmail`, which I will need some time to research

**Comment by kiwicopple** [comment]
Hey @izqalan - can you please describe how you used `AsyncStorage` in your PR https://github.com/supabase/gotrue-js/pull/14?

I've created a PR with an example here https://github.com/supabase/gotrue-js/pull/21 but it doesn't look like AsyncStorage matches the interface: 

![image](https://user-images.githubusercontent.com/10214025/98243554-122ff900-1fa9-11eb-9772-520a40324132.png)


Did you add a full wrapper around `AsyncStorage` to make it compatible?

**Comment by izqalan** [comment]
Hey @kiwicopple

hmm that's strange.
I just import `AsyncStorage` from `@react-native-community/async-storage` and specify it on `localStorage` option.
This is how I initialize `GoTrueClient` class previously on my React Native app.
![code](https://i.imgur.com/09mhH2A.png)
Also, it might be worth mentioning I'm using JavaScript for the app.

**Comment by kiwicopple** [comment]
Hey @izqalan  I mentioned you [here](https://github.com/supabase/supabase/issues/276#issuecomment-731209863), but I thought I'd drop a notification in this thread too since you're subscribed.

Do you have any public code for your RN app?

**Comment by tjg1** [comment]
@kiwicopple I've tried looking into this, but it appears your problem was fixed already with #24.

The example in your PR builds fine now.

**Comment by kiwicopple** [comment]
thanks for testing @tjg1 - I saw your comment in the PR 🙏 

Could I get a small favour, could you confirm the PR in our main repo works for you? https://github.com/supabase/supabase/pull/315

If it is, can you let me know if you're on Android or iOS? (I only have iOS and I'm still getting the error: `Could not read password grant params: EOF`. Looks like a server error, but the code works when I run it in a browser.

**Comment by tjg1** [comment]
hi @kiwicopple,

I have just tried this out. Indeed that error gets returned by the server. It works in a browser and in React Native _with a debugger attached_. But it seems that while debugging, the RN code is actually running in a web worker in my browser.

I will dig deeper into this. I have a jailbroken iOS device setup with https://github.com/nabla-c0d3/ssl-kill-switch2, so I can get the actual HTTP request made by RN and compare it to the one made by the browser.

**Comment by tjg1** [comment]
I've done that and reproduced it with cURL.

React Native on iOS sends `Content-Type: application/x-www-form-urlencoded` even though the body of the request is UTF-8 JSON. Your server gets confused and returns 400 `{"code":400,"msg":"Could not read password grant params: EOF"}`.

Changing the header to `Content-Type: text/plain`, the same request succeeds.

**Comment by irfaan** [comment]
Hi! This issue persists on the latest version of supabase-js (^1.17.0):

`undefined is not an object (evaluating 'this.localStorage.getItem')`

react-native: `17.0.1`
Supabase-js: `1.17.0`

Happens with and without `react-native-url-polyfill v. 1.3.0` (see https://github.com/facebook/react-native/issues/23922#issuecomment-648096619)

**Comment by m0a** [comment]
it's work!

"react-native": "0.64.3",
"@react-native-async-storage/async-storage": "^1.15.17",
"@supabase/supabase-js": "^1.30.0",

```
import { createClient } from '@supabase/supabase-js'
import AsyncStorage from '@react-native-async-storage/async-storage';

const supabaseUrl = "xxxxx"
const supabaseAnonKey = 'xxx'

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {localStorage: AsyncStorage})
```
