### ISSUE TITLE
Enable third party auth from access token and/or code

### ISSUE THREAD

**Issue by davitykale-zz** [supabase/gotrue-js#406]
# Feature request

Ability to use access token or other credential received from OAuth flow to enable third party auth.

## Is your feature request related to a problem? Please describe.

I am using Expo for my app which takes care a lot of the nuances in handling OAuth flows in a React Native / Expo managed app: https://docs.expo.io/guides/authentication/. Right now, trying to use the built-in provider flows from Supabase JS client is not working.

## Describe the solution you'd like

I would like a way to send an access token or other credential received from an OAuth flow to Supabase to facilitate the login.

## Describe alternatives you've considered

Not offering third party auth.

**Comment by fedorish** [comment]
Is the refreshToken approach going to work in with supabase-js 2.0 when `signIn` is replaced?

**Comment by pixtron** [comment]
> Is the refreshToken approach going to work in with supabase-js 2.0 when `signIn` is replaced?

You could try this in v2 instead of `singIn`
```ts
if (payload.params?.refresh_token) {
  const { data: { session, user}, error } = await supabase.auth.setSession(payload.params.refresh_token);
}

```

**Comment by beppek** [comment]
I'm having some issues with `supabase.auth.setSession` in 2.0.0-rc.10 where calling that method _seems_ to set the session, it returns the user and a new refresh_token. But calling `supabase.auth.getUser` or `supabase.auth.getSession` returns null for user and session respectively.

Maybe worth noting that I'm using this in a server context.

**Comment by alrightsure** [comment]
`supabase.auth.setSession` doesn't seem to work for this. The docs (and pixtron's example) seems to show that `setSession` takes a refresh token as its args, but according to its type defnition, it requires an entire session object:

"Sets the session data from the current session. If the current session is expired, setSession will take care of refreshing it to obtain a new session. If the refresh token in the current session is invalid and the current session has expired, an error will be thrown. If the current session does not contain at expires_at field, setSession will use the exp claim defined in the access token.

@param currentSession — The current session that minimally contains an access token, refresh token and a user."

**Comment by pixtron** [comment]
> `supabase.auth.setSession` doesn't seem to work for this. The docs (and pixtron's example) seems to show that `setSession` takes a refresh token as its args, but according to its type defnition, it requires an entire session object:

@alrightsure Your right, the signature of the method has changed in #467 shortly after i left the comment. Now it would be:
```ts
const {access_token, refresh_token} = payload.params;
if (access_token && refresh_token) {
  const { data: { session, user}, error } = await supabase.auth.setSession({access_token, refresh_token});
}
```

**Comment by tri2820** [comment]
Is there any way we can provide social `scopes` as params to `startAsync`?

**Comment by hf** [comment]
Hey everyone, this issue has been open for a while but I believe most of the underlying issues have been addressed.

Please switch to v2 of the client library to get all of the goodies. I'll close the issue for now.

**Comment by mchennupati** [comment]
> > `supabase.auth.setSession` doesn't seem to work for this. The docs (and pixtron's example) seems to show that `setSession` takes a refresh token as its args, but according to its type defnition, it requires an entire session object:
> 
> @alrightsure Your right, the signature of the method has changed in #467 shortly after i left the comment. Now it would be:
> 
> ```ts
> const {access_token, refresh_token} = payload.params;
> if (access_token && refresh_token) {
>   const { data: { session, user}, error } = await supabase.auth.setSession({access_token, refresh_token});
> }
> ```

When I try to set the session object using access and refresh tokens from an OAuth provider as above, I get this error :) 
[Unhandled promise rejection: ReferenceError: Can't find variable: Buffer]
 at node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:125:25 in decodeBase64URL

**Comment by fedorish** [comment]
> > > `supabase.auth.setSession` doesn't seem to work for this. The docs (and pixtron's example) seems to show that `setSession` takes a refresh token as its args, but according to its type defnition, it requires an entire session object:
> > 
> > 
> > @alrightsure Your right, the signature of the method has changed in #467 shortly after i left the comment. Now it would be:
> > ```ts
> > const {access_token, refresh_token} = payload.params;
> > if (access_token && refresh_token) {
> >   const { data: { session, user}, error } = await supabase.auth.setSession({access_token, refresh_token});
> > }
> > ```
> 
> When I try to set the session object using access and refresh tokens from an OAuth provider as above, I get this error :) [Unhandled promise rejection: ReferenceError: Can't find variable: Buffer] at node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:125:25 in decodeBase64URL



Try installing `buffer` via your package mange and then adding this to your `App.tsx`:
```
import { Buffer } from 'buffer';
global.Buffer = Buffer;

```

**Comment by mchennupati** [comment]
That worked for me, thanks !  setting the session, somehow still doesn't trigger the state change as it is not recognized as a SIGN IN I guess. But we can work round that using the data from the session object.
      supabase.auth.onAuthStateChange((_event, session) => {
        console.log(_event, session)
      })

**Comment by Mjelstad91** [comment]
With expo SDK 48 iOS is not working with redirect_to. I'm getting: `Validation Error: 'redirect_to' is not allowed`. Anyone else experiencing this?

**Comment by paule89123** [comment]
I get the following warning when setting the session with my access token and refresh token:

await supabase.auth.setSession({
        access_token: authResponse.params.access_token,
        refresh_token: authResponse.params.refresh_token
      })

Warning: "Provided value to SecureStore is larger than 2048 bytes. An attempt to store such a value will throw an error in SDK 35."

Anyone else encountered this?

**Comment by ChronSyn** [comment]
> I get the following warning when setting the session with my access token and refresh token (using expo-secure-store):
> 
> await supabase.auth.setSession({ access_token: authResponse.params.access_token, refresh_token: authResponse.params.refresh_token })
> 
> Warning: "Provided value to SecureStore is larger than 2048 bytes. An attempt to store such a value will throw an error in SDK 35."
> 
> Anyone else encountered this?

This isn't related to Supabase - instead, it's related to Expo securestore (https://docs.expo.dev/versions/latest/sdk/securestore/)

**Comment by paule89123** [comment]
Many thanks @ChronSyn. I wasn't sure if maybe supabase was storing more than it should be. 

I won't be storing anything besides the session info in secure-store. Reassuring to hear this won't be a problem. However, expo-secure-store says that it will throw an error in future SDK's, so I'm a little worried about this.
